language: scala # to trigger the build on JVM worker ('language: java' works the same)
env:
  - PLAY_VERSION=2.2.3 # Change to the latest version here
scala:
  - 2.10.3
before_script: 
  - cd weather-demo/
  - wget http://downloads.typesafe.com/play/2.2.3/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
